GET http://localhost:3333/todos

###

POST http://localhost:3333/todo/new
Content-Type: application/json

{
  "text": "Comprar dfgdgd"
}

###

DELETE http://localhost:3333/todo/delete/64efe3543589841a40e146a7

###

PUT http://localhost:3333/todo/complete/64f0926c688c40d855802c02